### ISSUE TITLE
line 3 server.php

### ISSUE THREAD

**Issue by tjoozey** [reactphp-legacy/gifsocket#1]
|ruby-1.9.3-p194| Tylers-MacBook-Pro in ~/Downloads/gifsocket
± |master ✓| → sudo php server.php
Password:

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /Users/tyler/Downloads/gifsocket/server.php on line 3

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:') in /Users/tyler/Downloads/gifsocket/server.php on line 3

**Comment by igorw** [comment]
Heya, you need to install the dependencies of the project [using composer](http://getcomposer.org).

Sorry, I only just saw this ticket now. I have added a note about this to the README file.

Side note: you shouldn't need `sudo`, since `8080` is not a privileged port.

**Comment by tjoozey** [comment]
The detect_unicode setting must be disabled.
Add the following to the end of your `php.ini`:
    detect_unicode = Off

## 

Tyler Johnson
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by igorw** [comment]
Yeah, that's one of the things the composer install script checks for. There's a few other settings you need to watch out for as well.

**Comment by tjoozey** [comment]
Others things I need to watch out for meaning I need to install more dependencys? Composer is installed, please add this to the readme to help newbies like me out hehe  

## 

Tyler Johnson
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
